# Generated by Django 5.1.7 on 2025-03-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_remove_customuser_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("followers", "Followers Only"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
