# Generated by Django 5.1.7 on 2025-03-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_author_comment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="comment",
            unique_together={("author", "post", "text")},
        ),
    ]
