# Generated by Django 5.1.7 on 2025-03-31 12:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_privacy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="like",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="posts_post_author__19d68b_idx",
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="posts_post_created_dadbfe_idx",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="text",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="parent_comment",
            new_name="parent",
        ),
        migrations.RenameField(
            model_name="follow",
            old_name="following",
            new_name="followed",
        ),
        migrations.AlterUniqueTogether(
            name="comment",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("follower", "followed")},
        ),
    ]
