# Generated by Django 5.1.7 on 2025-04-01 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_author_alter_post_privacy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={},
        ),
    ]
